// Seed data for initial app state

import { User, Vendor, MenuItem } from '@/types';

export const seedUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Johnson',
    email: 'sarah@university.edu',
    role: 'buyer',
    phone: '555-0101',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-2',
    name: 'Mike Chen',
    email: 'mike@university.edu',
    role: 'vendor',
    phone: '555-0102',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-3',
    name: 'Emma Rodriguez',
    email: 'emma@university.edu',
    role: 'vendor',
    phone: '555-0103',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-4',
    name: 'David Park',
    email: 'david@university.edu',
    role: 'runner',
    phone: '555-0104',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-cafeteria',
    name: 'University Cafeteria',
    email: 'cafeteria@university.edu',
    role: 'vendor',
    phone: '555-0100',
    createdAt: new Date().toISOString(),
  },
];

export const seedVendors: Vendor[] = [
  {
    id: 'vendor-cafeteria',
    userId: 'user-cafeteria',
    name: 'University Cafeteria',
    description: 'Official campus dining with fresh, affordable meals daily',
    cuisineType: 'American, International',
    image: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=500&h=300&fit=crop',
    rating: 4.5,
    isActive: true,
    isCafeteria: true,
    preparationTime: 15,
  },
  {
    id: 'vendor-1',
    userId: 'user-2',
    name: "Mike's Asian Kitchen",
    description: 'Authentic Asian cuisine made by a culinary arts student',
    cuisineType: 'Asian, Chinese, Thai',
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=500&h=300&fit=crop',
    rating: 4.8,
    isActive: true,
    isCafeteria: false,
    preparationTime: 25,
  },
  {
    id: 'vendor-2',
    userId: 'user-3',
    name: "Emma's Healthy Bowls",
    description: 'Nutritious bowls and smoothies for the health-conscious student',
    cuisineType: 'Healthy, Vegetarian, Vegan',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop',
    rating: 4.7,
    isActive: true,
    isCafeteria: false,
    preparationTime: 20,
  },
];

export const seedMenuItems: MenuItem[] = [
  // University Cafeteria items
  {
    id: 'item-cafe-1',
    vendorId: 'vendor-cafeteria',
    name: 'Classic Burger & Fries',
    description: 'Juicy beef patty with lettuce, tomato, and crispy fries',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    preparationTime: 12,
    category: 'Main Course',
    isAvailable: true,
  },
  {
    id: 'item-cafe-2',
    vendorId: 'vendor-cafeteria',
    name: 'Grilled Chicken Salad',
    description: 'Fresh greens with grilled chicken, veggies, and balsamic vinaigrette',
    price: 9.49,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop',
    preparationTime: 10,
    category: 'Salads',
    isAvailable: true,
  },
  {
    id: 'item-cafe-3',
    vendorId: 'vendor-cafeteria',
    name: 'Margherita Pizza',
    description: 'Classic tomato, mozzarella, and basil pizza',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',
    preparationTime: 15,
    category: 'Pizza',
    isAvailable: true,
  },
  {
    id: 'item-cafe-4',
    vendorId: 'vendor-cafeteria',
    name: 'Breakfast Burrito',
    description: 'Eggs, cheese, sausage, and salsa wrapped in a flour tortilla',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    preparationTime: 8,
    category: 'Breakfast',
    isAvailable: true,
  },

  // Mike's Asian Kitchen items
  {
    id: 'item-mike-1',
    vendorId: 'vendor-1',
    name: 'Pad Thai',
    description: 'Stir-fried rice noodles with shrimp, peanuts, and lime',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=300&fit=crop',
    preparationTime: 20,
    category: 'Thai',
    isAvailable: true,
  },
  {
    id: 'item-mike-2',
    vendorId: 'vendor-1',
    name: 'General Tso Chicken',
    description: 'Crispy chicken in sweet and spicy sauce with steamed rice',
    price: 10.99,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&h=300&fit=crop',
    preparationTime: 18,
    category: 'Chinese',
    isAvailable: true,
  },
  {
    id: 'item-mike-3',
    vendorId: 'vendor-1',
    name: 'Vegetable Spring Rolls',
    description: 'Crispy rolls filled with fresh vegetables, served with sweet chili sauce',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&h=300&fit=crop',
    preparationTime: 10,
    category: 'Appetizers',
    isAvailable: true,
  },

  // Emma's Healthy Bowls items
  {
    id: 'item-emma-1',
    vendorId: 'vendor-2',
    name: 'Buddha Bowl',
    description: 'Quinoa, roasted chickpeas, avocado, kale, and tahini dressing',
    price: 10.49,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    preparationTime: 15,
    category: 'Bowls',
    isAvailable: true,
  },
  {
    id: 'item-emma-2',
    vendorId: 'vendor-2',
    name: 'Acai Berry Bowl',
    description: 'Acai blend topped with granola, fresh berries, and honey',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=300&fit=crop',
    preparationTime: 10,
    category: 'Smoothie Bowls',
    isAvailable: true,
  },
  {
    id: 'item-emma-3',
    vendorId: 'vendor-2',
    name: 'Green Energy Smoothie',
    description: 'Spinach, banana, mango, and almond milk',
    price: 6.49,
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400&h=300&fit=crop',
    preparationTime: 5,
    category: 'Smoothies',
    isAvailable: true,
  },
];
