// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both common env var names
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY) as string | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Provide a clearer, actionable error to help during local dev
  // Common causes:
  // 1) App opened via file:// or without Vite/preview (import.meta.env is undefined)
  // 2) .env missing or variables not prefixed with VITE_
  // 3) Wrong variable names (use VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY)
  // 4) Supabase project not created or deleted
  throw new Error(
    [
      '❌ Supabase is not configured: missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY.',
      '',
      '📋 See SUPABASE_SETUP_REQUIRED.md for setup instructions.',
      '',
      'Quick fix:',
      ' 1. Create a Supabase project at https://supabase.com/dashboard',
      ' 2. Update .env file with your project URL and anon key',
      ' 3. Run: pnpm dev',
      '',
      'Current values:',
      `   VITE_SUPABASE_URL: ${SUPABASE_URL || 'NOT SET'}`,
      `   VITE_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'NOT SET'}`,
    ].join('\n')
  );
}

// Import the supabase client like this:
// import { supabase } from ":/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});